### PR TITLE
docs: update checkout GitHub Action to the latest version

### PR DESCRIPTION
**Pull request by froblesmartin**

### CODE REVIEW

**Comment by froblesmartin** [comment]
@dbmeneses @cody-simms-sonarsource @david-cho-lerat-sonarsource

**Comment by dbmeneses** [comment]
Hi @froblesmartin were you able to test this action with checkout v4?

**Comment by froblesmartin** [comment]
> Hi @froblesmartin were you able to test this action with checkout v4?

Yes, we are using it since I opened this PR 😉

**Review by dbmeneses — APPROVED** [review]

**Comment by dbmeneses** [comment]
Thanks @froblesmartin

**Pull request merged**
