### PR TITLE
Bugfix/remove set sonar token

### PR DESCRIPTION
**Pull request by rcmlee99**
I am using Github Actions to configure sonar cloud

Following is snippet of the code
steps:
- uses: actions/checkout@v2
- name: Use Node.js {{ matrix.node-version }} uses: actions/setup-node@v1 with: node-version: {{ matrix.node-version }}
- name: SonarCloud Scan
uses: sonarsource/sonarcloud-github-action@master
env:
GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }} SONAR_TOKEN: {{ secrets.SONAR_TOKEN }}

Following is the sonar-project.propertiest
sonar.organization=“react-hook-form”
sonar.projectKey=“react-hook-form_error-message”
sonar.sources="./src"

The Sonar Cloud analyse successful but your entry point checking for SONAR TOKEN which should be secrets.SONAR_TOKEN.

### CODE REVIEW

**Comment by rcmlee99** [comment]
Please have a look at this build why it's fail https://github.com/react-hook-form/error-message/runs/1941420060?check_suite_focus=true. 
The Sonar Analyse is complete but the build fail because of same reason.

**Comment by rcmlee99** [comment]
The check SONAR_TOKEN is not needed. If need to check, please check on env.SONAR_TOKEN or secrets.SONAR_TOKEN.

**Comment by itavero** [comment]
I'm running into the same issue on one of my repositories, now that another user has [opened a PR](https://github.com/itavero/homebridge-z2m/pull/78), the check is also failing because it can't find the `SONAR_TOKEN` environment variable.

However, the check is correct, I believe. Like you've mentioned, in the GitHub workflow yaml file you set the environment variable:
```yaml
env:
   GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
   SONAR_TOKEN: {{ secrets.SONAR_TOKEN }}
```

Within the container `secrets.SONAR_TOKEN` isn't known, which is why it is passed as the `SONAR_TOKEN` environment variable.

But the problem remains, why isn't it finding the environment variable.. Hopefully someone else can shed a light on it.

**Comment by tom-vanbraband-sonarsource** [comment]
@itavero The problem is that GitHub does not expose repository secrets in the actions running on an external PR. You can disable this behaviour if you want, however if anyone can open up an external PR on your repository they can also get access to your repository secrets. See this blog post by GitHub for more information: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by itavero** [comment]
Just found out about that as well. Currently trying the `workflow_run` trigger as mentioned in [this blogpost from GitHub](https://securitylab.github.com/research/github-actions-preventing-pwn-requests).

**Comment by itavero** [comment]
My attempt with the `workflow_run` approach wasn't successful, so I used `pull_request_target` instead (with an additional label check).
To get this action working I used the following step configuration, which seems to work correctly for me:

```yaml
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.provider=github
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.pullrequest.github.token.secured=${{ secrets.GITHUB_TOKEN }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
```

Leaving this here in case others also come across this PR as well when they are running to this issue.

**Pull request closed without merging**
