### PR TITLE
fix: add cleanup script for perms

### PR DESCRIPTION
**Pull request by zaosoula**
Based on:
- https://github.com/SonarSource/sonarqube-scan-action/pull/25
- https://github.com/SonarSource/sonarqube-scan-action/pull/33

Related to:
- https://github.com/SonarSource/sonarqube-scan-action/issues/22
- https://github.com/SonarSource/sonarqube-scan-action/issues/31
- https://community.sonarsource.com/t/github-actions-sonarcloud-github-action-permissions-issue/41609
- https://community.sonarsource.com/t/github-actions-sonarqube-scan-action-failing-with-local-runners/58272

### CODE REVIEW

**Review by spike008t — APPROVED** [review]

**Comment by drashy** [comment]
Can someone merge this please :)

**Comment by andrioli** [comment]
Same issue here.

**Comment by scadenalcrs** [comment]
+1

**Comment by spike008t** [comment]
@nawar-hamo-sonarsource could you please have a look on that PR?

**Comment by sre-bankly** [comment]
+1

**Review by dgosantos89 — APPROVED** [review]

**Comment by piti118** [comment]
Pretty please + 1.

**Comment by dgosantos89** [comment]
@nawar-hamo-sonarsource

**Comment by csaba-feher-sonarsource** [comment]
It has already been applied to the master; thank you for your contribution.

**Pull request closed without merging**
