### PR TITLE
Remove token requirement

### PR DESCRIPTION
**Pull request by npereiraexpedia**
Since SonarQube has the option to allow scan to run without authentication token, this change removes the hard requirement from the token from the action.

### CODE REVIEW

**Review by jayvdb — APPROVED** [review]

**Comment by npereiraexpedia** [comment]
@jayvdb thanks for the approval. Had to rebase the branch, do you mind re-approving so it can be merged?

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
My review doesnt count, as I am not one of the committers / collaborators here.

**Comment by emranbm** [comment]
Seems helpful. It lets *fork pull requests* be analyzed before merging. Since there is no access to repo secrets in such PRs.  
Any update on this?

**Comment by emranbm** [comment]
Hey @npereiraexpedia,
Are you sure it can be run without the token? I tried it locally and it was erroring the exact point!
```
ERROR: Error during SonarScanner execution
ERROR: You're not authorized to run analysis. No sonar.login or SONAR_TOKEN env variable was set
```

**Pull request closed without merging**
